# Signup Types
SIGNUP_TYPE_SELF = "SELF"
SIGNUP_TYPE_ADMIN = "ADMIN"

SIGNUP_TYPE_CHOICES = (
    (SIGNUP_TYPE_SELF, "Self"),
    (SIGNUP_TYPE_ADMIN, "Admin"),
)


# Role Codes
ROLE_ADMIN = "ADMIN"
ROLE_ANALYST = "ANALYST"
ROLE_CLIENT = "CLIENT"

ROLE_CODE_CHOICES = (
    (ROLE_ADMIN, "Admin"),
    (ROLE_ANALYST, "Analyst"),
    (ROLE_CLIENT, "Client"),
)


# Transaction type
TRANSACTION_TYPE_INCOME = "income"
TRANSACTION_TYPE_EXPENSE = "expense"

TRANSACTION_TYPE_CHOICES = (
    (TRANSACTION_TYPE_INCOME, "Income"),
    (TRANSACTION_TYPE_EXPENSE, "Expense"),
)

TRANSACTION_AUDIT_ACTION_CREATE = "create"
TRANSACTION_AUDIT_ACTION_UPDATE = "update"
TRANSACTION_AUDIT_ACTION_DELETE = "delete"

TRANSACTION_AUDIT_ACTION_CHOICES = (
    (TRANSACTION_AUDIT_ACTION_CREATE, "Create"),
    (TRANSACTION_AUDIT_ACTION_UPDATE, "Update"),
    (TRANSACTION_AUDIT_ACTION_DELETE, "Delete"),
)